[env]
BROKER_URL = "amqp://localhost:5672"
DB_HOST = "localhost"
DB_PASSWORD = "autoplaylist"
DOMAIN = "localhost:8080"
JWT_SECRET = "changeit"
LOG_FILTER = "info,autoplaylist_core=trace,autoplaylist_api=trace"
WEBAPP_URL = "http://localhost:3000"
