repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: .rs$
      - id: end-of-file-fixer
        exclude: .rs$
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
      - id: cargo-check
      - id: clippy
        args: ["--tests", "--", "-D", "warnings"]
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 2.0.0
    hooks:
      - id: sqlfluff-lint
        args:
          - -n
          - --ignore
          - lexing,parsing
          - --dialect
          - postgres
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier
          - prettier-plugin-organize-imports
