version: "3"

volumes:
  rabbitmq:
  postgres:

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: autoplaylist
      POSTGRES_USER: autoplaylist
      POSTGRES_PASSWORD: autoplaylist
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3
    ports:
      - 5672:5672
    volumes:
      - rabbitmq:/var/lib/rabbitmq
