version: '3'

services:
  broker:
    image: rabbitmq:3
    ports:
    - 5672:5672

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: autoplaylist
      POSTGRES_PASSWORD: autoplaylist
      POSTGRES_USER: autoplaylist
    ports:
    - 5432:5432

  wiremock:
    image: wiremock/wiremock
    ports:
    - 8081:8080
    volumes:
    - ./docker-compose/wiremock:/home/wiremock/mappings
