[env]
DATABASE_PASSWORD = "autoplaylist"
DATABASE_SECRET = "changeit"
DATABASE_URL = "postgres://autoplaylist:autoplaylist@localhost:5432/autoplaylist"
JWT_SECRET = "changeit"
LOG_FILTER = "autoplaylist=trace,autoplaylist_api=trace,autoplaylist_common=trace,info"
LOG_JSON = "false"
