apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "autoplaylist-api.fullname" . }}
  labels:
    {{- include "autoplaylist-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "autoplaylist-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "autoplaylist-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "autoplaylist-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- range $key, $val := .Values.env }}
          - name: {{ $key }}
            value: {{ $val | quote }}
          {{- end }}
          {{- range $key, $val := .Values.secrets }}
          - name: {{ $key }}
            valueFrom:
              secretKeyRef:
                name: {{ $val.name }}
                key: {{ $val.key }}
          {{- end }}
          - name: DATABASE_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Values.existingDatabaseSecret.name | default (include "autoplaylist-api.dbSecretName" .) }}
                key: {{ .Values.existingDatabaseSecret.key | default "secret" }}
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Values.existingJwtSecret.name | default (include "autoplaylist-api.jwtSecretName" .) }}
                key: {{ .Values.existingJwtSecret.key | default "secret" }}
          - name: SPOTIFY_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: {{ .Values.spotifySecret.name }}
                key: {{ .Values.spotifySecret.clientIdKey }}
          - name: SPOTIFY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: {{ .Values.spotifySecret.name }}
                key: {{ .Values.spotifySecret.clientSecretKey }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
