name: Release

permissions:
  contents: write

on:
  push:
    tags: [v*]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Create release
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
