{{- $storeName := include "autoplaylist.secretStoreName" .  }}
{{- range $secretName, $secret := .Values.externalSecrets.secrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $secretName }}
spec:
  refreshInterval: {{ $secret.refreshInterval | default "15s" }}
  secretStoreRef:
    name: {{ $storeName }}
    kind: SecretStore
  target:
    name: {{ $secretName }}
  {{- with $secret.data }}
  data:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
