{{- if .Values.externalSecrets.store.create -}}
{{- $storeName := include "autoplaylist.secretStoreName" . -}}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ $storeName }}
  labels:
    {{- include "autoplaylist.labels" . | nindent 4 }}
spec:
  {{- with .Values.externalSecrets.store.provider }}
  provider:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
